version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/node

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
      - run:
          name: Run npm install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn test:cover

